# Generated by Django 4.1 on 2023-01-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default_profile_pic.jpg", upload_to="users/profile_pics"
            ),
        ),
    ]
