# Generated by Django 4.1 on 2023-01-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_image_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, max_length=300, null=True, upload_to="post_images/"
            ),
        ),
    ]
